language: java
cache:
  directories:
   - $HOME/.m2
matrix:
    include:
        - os: linux
          jdk: openjdk8
        - os: linux
          jdk: oraclejdk11
        - os: linux
          jdk: openjdk11
        - os: osx
          osx_image: xcode9.3
        - os: osx
          osx_image: xcode10.1
    allow_failures:
        - os: osx
before_install:
 - date -u
 - uname -a
 - env | sort
branches:
 only:
   - master
notifications:
 email:
  - open-identity-platform@googlegroups.com
install:
  - echo 'install'
script:
  - mvn -B -DskipTests install && mvn -q -B test